In [1]:
import pandas as pd
import numpy as np

In [2]:
import re
import nltk
from nltk.tokenize import word_tokenize

In [3]:
df_test = pd.read_csv('data_test_nostemstop_preprocessed.csv',sep=";")

In [4]:
df_train = pd.read_csv('data_train_nostemstop_preprocessed.csv',sep=";")

In [5]:
df_test.head()

,Index,Tweet,HS,Abusive,HS_Individual,HS_Group,HS_Religion,HS_Race,HS_Physical,HS_Gender,HS_Other,HS_Weak,HS_Moderate,HS_Strong,Tweet_Parsed
0,1,GANTENG TAPI BERENGSEK!!! BUAT APA?!!\r\nWHO D...,1,1,1,0,0,0,0,0,1,1,0,0,ganteng tapi berengsek buat apa who do you thi...
1,2,Sakit jiwa kali yah..,0,0,0,0,0,0,0,0,0,0,0,0,sakit jiwa kali
2,3,"Does insulting one for being ""Cina"", ""Kafir"", ...",0,1,0,0,0,0,0,0,0,0,0,0,does insulting one for being cina kafir make y...
3,4,USER USER Karena partaimu pdip itu bajingan',1,1,0,1,0,0,0,0,1,0,1,0,user user karena partaimu partai demokrasi ind...
4,5,USER USER Jgn salah itu janji jokowi yg di tun...,1,1,1,0,0,0,0,0,1,1,0,0,user user jangan salah itu janji jokowi di tu...

In [6]:
kolom_yang_diinginkan = ['Tweet_Parsed', 'HS']

In [7]:
df_train = df_train[kolom_yang_diinginkan]

In [8]:
df_train

                                            Tweet_Parsed  HS
0       kadang will be kind enough to show you how to...   0
1                   ternyata komunis juga bisa menangis    0
2      user user kenapa harus bom  seperti  benar men...   0
3      user sumpah kaya kalau habis iya dilanjut olim...   0
4      rt user user user user user fungsi media sosia...   1
...                                                  ...  ..
13239  somebody sanity is not something that you can ...   0
13240                user user user user kotbur  mampus    1
13241   news scarlett johansson akhirnya mengundurkan...   0
13242  if you call me to take your order  i will pas ...   1
13243  kenali aku lebih dalam maka kamu akan mengerti...   0

[13244 rows x 2 columns]

In [22]:
df_train.to_csv('data_train_clean.csv', index=False)

In [9]:
df_test = df_test[kolom_yang_diinginkan]

In [10]:
df_test

                                           Tweet_Parsed  HS
0     ganteng tapi berengsek buat apa who do you thi...   1
1                                     sakit jiwa kali     0
2     does insulting one for being cina kafir make y...   0
3     user user karena partaimu partai demokrasi ind...   1
4     user user jangan salah itu janji jokowi  di tu...   1
...                                                 ...  ..
3675  bangsat  rt fuch boy sehun so whose falsetto i...   1
3676  karakter kartun  mendeskripsikan karakter luha...   0
3677  state killing encounter had been the forte of ...   0
3678  user user harusnya nanti fahri hamzah di kasih...   1
3679  user pertanyaan saya adakah syariat islam  men...   0

[3680 rows x 2 columns]

In [11]:
df_test.to_csv('data_test_clean.csv', index=False)

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, roc_auc_score, log_loss
from sklearn.metrics import classification_report, confusion_matrix

In [13]:
x_train = df_train['Tweet_Parsed']

In [14]:
x_test = df_test['Tweet_Parsed']

In [15]:
y_train = df_train['HS']

In [16]:
y_test = df_test['HS']

In [17]:
x_train.head()

0     kadang will be kind enough to show you how to...
1                 ternyata komunis juga bisa menangis
2    user user kenapa harus bom  seperti  benar men...
3    user sumpah kaya kalau habis iya dilanjut olim...
4    rt user user user user user fungsi media sosia...
Name: Tweet_Parsed, dtype: object

In [18]:
x_test.head()

0    ganteng tapi berengsek buat apa who do you thi...
1                                    sakit jiwa kali
2    does insulting one for being cina kafir make y...
3    user user karena partaimu partai demokrasi ind...
4    user user jangan salah itu janji jokowi  di tu...
Name: Tweet_Parsed, dtype: object

In [19]:
y_train.head()

0    0
1    0
2    0
3    0
4    1
Name: HS, dtype: int64

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [21]:
vectorizer = TfidfVectorizer()
train_tfidf= vectorizer.fit_transform(x_train)

In [22]:
TFIDF_train=pd.DataFrame(train_tfidf.toarray(),columns=vectorizer.get_feature_names_out())
TFIDF_train.head()

,aaaaaaah,aaaamiiiiiiinnnn,aaid,aamiin,aamiinkan,aarman,aaron,aarze,ab,aba,...,zona,zone,zoom,zorn,zouk,zuck,zul,zulkifli,zumi,zzed
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
train_tfidf.shape

(13244, 22459)

In [24]:
col=TFIDF_train.columns

In [25]:
train_tfidf.shape

(13244, 22459)

In [26]:
from sklearn import svm
svm_class = svm.LinearSVC( random_state=42)
svm_class.fit(train_tfidf, y_train)

C:\Users\gilan\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(

LinearSVC(random_state=42)

In [27]:
test_tfidf = vectorizer.transform(x_test)

In [28]:
TFIDF_test=pd.DataFrame(test_tfidf.toarray(),columns=vectorizer.get_feature_names_out())
TFIDF_test.head()

,aaaaaaah,aaaamiiiiiiinnnn,aaid,aamiin,aamiinkan,aarman,aaron,aarze,ab,aba,...,zona,zone,zoom,zorn,zouk,zuck,zul,zulkifli,zumi,zzed
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
test_svm_class=svm_class.predict(test_tfidf)

In [30]:
print('\nClassification Report\n')
print(classification_report(y_test, test_svm_class, target_names=['0','1']))

Classification Report

              precision    recall  f1-score   support

           0       0.82      0.87      0.85      2204
           1       0.79      0.72      0.75      1476

    accuracy                           0.81      3680
   macro avg       0.81      0.80      0.80      3680
weighted avg       0.81      0.81      0.81      3680