In [1]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.tokenize import word_tokenize

In [2]:
df_test = pd.read_csv('data_test_clean.csv')
df_train = pd.read_csv('data_train_clean.csv')

In [3]:
df_train.head()

                                        Tweet_Parsed  HS
0   kadang will be kind enough to show you how to...   0
1               ternyata komunis juga bisa menangis    0
2  user user kenapa harus bom  seperti  benar men...   0
3  user sumpah kaya kalau habis iya dilanjut olim...   0
4  rt user user user user user fungsi media sosia...   1

#### Split Data

In [4]:
x_train = df_train['Tweet_Parsed']
x_test = df_test['Tweet_Parsed']

In [5]:
y_train = df_train['HS']
y_test = df_test['HS']

In [6]:
x_train.head()

0     kadang will be kind enough to show you how to...
1                 ternyata komunis juga bisa menangis
2    user user kenapa harus bom  seperti  benar men...
3    user sumpah kaya kalau habis iya dilanjut olim...
4    rt user user user user user fungsi media sosia...
Name: Tweet_Parsed, dtype: object

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
train_tfidf= vectorizer.fit_transform(x_train)

In [8]:
TFIDF_train=pd.DataFrame(train_tfidf.toarray(),columns=vectorizer.get_feature_names_out())
TFIDF_train.head()

,aaaaaaah,aaaamiiiiiiinnnn,aaid,aamiin,aamiinkan,aarman,aaron,aarze,ab,aba,...,zona,zone,zoom,zorn,zouk,zuck,zul,zulkifli,zumi,zzed
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
col=TFIDF_train.columns

In [10]:
train_tfidf.shape

(13244, 22459)

In [11]:
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC
import warnings
warnings.filterwarnings('ignore')

SVM_class = make_pipeline(SVC())
SVM_class.fit(train_tfidf, y_train)

Pipeline(steps=[('svc', SVC())])

**Testing**

In [12]:
test_tfidf = vectorizer.transform(x_test)

In [13]:
TFIDF_test=pd.DataFrame(test_tfidf.toarray(),columns=vectorizer.get_feature_names_out())
TFIDF_test.head()

,aaaaaaah,aaaamiiiiiiinnnn,aaid,aamiin,aamiinkan,aarman,aaron,aarze,ab,aba,...,zona,zone,zoom,zorn,zouk,zuck,zul,zulkifli,zumi,zzed
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
y_predict=SVM_class.predict(test_tfidf)

In [15]:
from sklearn.metrics import classification_report
print('\nClassification Report\n')
print(classification_report(y_test, y_predict, target_names=['0','1']))

Classification Report

              precision    recall  f1-score   support

           0       0.82      0.91      0.86      2204
           1       0.84      0.70      0.76      1476

    accuracy                           0.82      3680
   macro avg       0.83      0.80      0.81      3680
weighted avg       0.83      0.82      0.82      3680